server:
  port: 8081

spring:
  application:
    name: game-monitor
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:file:./data/gamemonitor
    username: admin
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
